name: Test Javascript
on:
  push:
    paths:
      - .github/workflows/test-javascript.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd javascript
          yarn install
      - name: Test
        run: |
          cd javascript
          yarn test
